# Site settings
title:       Jekyll 
tagline:     "Des ressources pour l'utilisation de Jekyll"
description: "J'ai très vite été séduit par Jekyll et c'est ici que je partage cette idylle..."
baseurl: "" # the subpath of your site, e.g. /blog/
baseurl:     ""
url:         "http://jmarck4.github.io/"

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# About/contact
author:
  name:              Jean-Marc Kraëber
  url:               https://twitter.com/BlogOnWordPress
  email:             jmarck4@gmail.com

# Custom vars
version:             1.0.1


# Social icons
show_social_icons: true
github_username: jmarck4
twitter_username: BlogOnWordPress

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
